/*
 * The 2018 theme.
 *
 * It is built by a tool from archived snapshots, so the checks that matter
 * are about the build being sound and the switch being safe - not about how
 * any individual rule looks.
 */
'use strict';

const test = require('node:test');
const assert = require('node:assert');
const { read, sitePages, unscopedSelectors, brokenKeyframes } = require('./helpers.js');

const THEME = read('css/theme2018.css');

test('every rule in the theme is scoped, so it cannot leak', () => {
  /* One unscoped rule - :root in particular - would restyle the whole site
   * for everybody the moment the file loaded. */
  assert.deepStrictEqual(unscopedSelectors(THEME, 'html.theme-2018'), []);
});

test('the theme\'s animations survived being scoped', () => {
  assert.deepStrictEqual(brokenKeyframes(THEME), [],
    'a prefixed @keyframes is invalid and kills the animation silently');
});

test('the theme carries no other site\'s name', () => {
  assert.ok(!/rolimon|koromon|coromon|colimon/i.test(THEME));
});

test('the theme references no dead archive URLs', () => {
  assert.ok(!/web\.archive\.org|web-static\.archive\.org/.test(THEME));
});

test('the switch is off unless asked for, and cannot be turned on by accident', () => {
  const theme = read('assets/js/theme.js');
  assert.match(theme, /parsed\.theme2018 === true/, 'only an explicit true counts');
  assert.match(theme, /catch \(error\) \{[\s\S]{0,200}return false/, 'bad storage must fall back');
});

test('the stylesheet ships disabled so nobody downloads it uninvited', () => {
  sitePages()
    .filter(([, html]) => html.includes('theme_2018_stylesheet'))
    .forEach(([name, html]) => {
      assert.match(html, /id="theme_2018_stylesheet" disabled>/, `${name}`);
    });
});

test('the theme loads in <head>, so there is no flash of the wrong skin', () => {
  sitePages()
    .filter(([, html]) => html.includes('theme.js'))
    .forEach(([name, html]) => {
      const head = html.indexOf('</head>');
      assert.ok(html.indexOf('assets/js/theme.js') < head, `${name} loads theme.js too late`);
      assert.ok(html.indexOf('theme_2018_stylesheet') < head, `${name} links the sheet too late`);
    });
});

test('every page that has the site chrome offers the theme', () => {
  const missing = sitePages()
    .filter(([name, html]) => html.includes('/css/wolimons.css') && !html.includes('theme_2018_stylesheet'))
    .map(([name]) => name);
  assert.deepStrictEqual(missing, []);
});

test('the preference is registered, defaults off, and is reset with the others', () => {
  const prefs = read('assets/js/prefs.js');
  assert.match(prefs, /theme2018: false/);
  assert.match(prefs, /wolimons:theme/, 'other open tabs need telling');
  assert.ok(read('preferences/index.html').includes('data-pref="theme2018"'));
  assert.ok(read('preferences/index.html').includes('Use 2018 Theme'));
});

test('the theme is reproducible from the tool, not hand-edited', () => {
  assert.ok(require('node:fs').existsSync(require('path').join(__dirname, '..', 'tools', 'build-theme2018.py')));
  assert.match(THEME, /Do not edit this file\. Re-run the tool\./);
});

test('the Discord panel is ours, not a dead iframe', () => {
  const home = read('index.html');
  assert.ok(home.includes('id="discord_widget"'));
  assert.ok(!/discordapp\.com\/widget\?id=/.test(home), 'the raw iframe shows an error when the widget is off');
  assert.ok(home.includes('/css/discord-widget.css'));
  assert.ok(home.includes('/assets/js/discord-widget.js'));
});

test('the Discord panel stylesheet is scoped and free of dead assets', () => {
  const css = read('css/discord-widget.css');
  assert.ok(!/url\(/.test(css), '2018 Discord CDN assets are long gone');
  assert.ok(!/@font-face/.test(css));
  assert.deepStrictEqual(unscopedSelectors(css, '.wolimons_discord'), []);
  assert.deepStrictEqual(brokenKeyframes(css), []);
});

test('the panel uses the invite already in the site', () => {
  assert.match(read('proxy/api.js'), /DISCORD_INVITE_CODE \|\| 'vCwRzWSMf'/);
  assert.match(read('proxy/api.js'), /DISCORD_GUILD_ID \|\| '1490444783435518013'/);
});
