#!/usr/bin/env python
"""Build css/theme2018.css from the 2018 Rolimon's Wayback snapshots.

Usage:  python tools/build-theme2018.py <extracted-snapshot-dir> [outfile]

The 2018 site was Bootswatch 4.1.2 "Slate" plus a small site.css of its own.
Both are lifted verbatim - the same way every other page on this site was
built from a snapshot - and then scoped so they only apply when the reader
has turned the theme on:

    .card { ... }            ->   html.theme-2018 .card { ... }
    :root { --primary: ... } ->   html.theme-2018 { --primary: ... }

Scoping rather than replacing matters. Wolimons has a lot of markup the 2018
site never had - trade ad rows, the admin panel, badge grids - and if the
modern stylesheet were simply swapped out those would come out unstyled. The
2018 rules layer on top instead, so what 2018 had a look for gets it, and
everything else keeps working.

@keyframes and @font-face bodies are left alone: their inner blocks are
percentages and descriptors, not selectors, and prefixing them breaks them.
"""
import os
import re
import sys

from cssscope import scope_css

def rebrand(css):
    """No other site's name survives into ours, in a comment or a URL."""
    css = re.sub(r'/\*[\s\S]*?\*/', '', css)
    css = re.sub(r'url\((["\']?)(?:https?:)?//[^)]*?rolimons\.com/([^)"\']*)\1\)',
                 r'url(\1/\2\1)', css, flags=re.I)
    return css


sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))


def main():
    if len(sys.argv) < 2:
        sys.exit(__doc__)
    src = sys.argv[1]
    out = sys.argv[2] if len(sys.argv) > 2 else 'css/theme2018.css'

    def read(name):
        with open(os.path.join(src, name), encoding='utf-8', errors='replace') as handle:
            return handle.read()

    pieces = []
    for name, label in (('f5.css', 'Bootswatch 4.1.2 Slate, as the 2018 site served it'),
                        ('f4.css', "the 2018 site's own site.css")):
        raw = rebrand(read(name))
        scoped = scope_css(raw, 'html.theme-2018')
        pieces.append(f'/* ---- {label} ---- */\n{scoped}')

    banner = (
        '/*\n'
        ' * Wolimons - the 2018 theme.\n'
        ' *\n'
        ' * Built by tools/build-theme2018.py from Wayback snapshots of the 2018-2019\n'
        ' * site, the same way every other page here was built from a snapshot. Two\n'
        ' * stylesheets are lifted verbatim: Bootswatch 4.1.2 Slate, which is what the\n'
        ' * site ran on, and the small site.css it shipped alongside it.\n'
        ' *\n'
        ' * Every rule is scoped to html.theme-2018, so none of it applies until the\n'
        ' * reader turns the theme on in /preferences. It layers over the modern\n'
        ' * stylesheets rather than replacing them - Wolimons has a lot of markup the\n'
        ' * 2018 site never had, and swapping the sheet out wholesale would leave the\n'
        ' * admin panel and the trade ad board unstyled.\n'
        ' *\n'
        ' * Do not edit this file. Re-run the tool.\n'
        ' */\n'
    )

    with open(out, 'w', encoding='utf-8') as handle:
        handle.write(banner + '\n'.join(pieces))
    print(f'wrote {out} ({os.path.getsize(out)} bytes)')


if __name__ == '__main__':
    main()
